/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
       // TestCases tests = new TestCases(); // Initialize your test class
       // AmazonSearch search = new AmazonSearch();
      // CountHyperlinks count = new CountHyperlinks();
       // LinkedinPost linkpost = new LinkedinPost();
         // GoogleNameLinks name = new GoogleNameLinks();
        // LinkedInImagePost imgpost = new LinkedInImagePost();
        //NestedFrames nesframes = new NestedFrames();
         // AlertPrompt alert = new AlertPrompt();
        // IMDB_Ratings imdb = new IMDB_Ratings();
         //WindowHandling handle = new WindowHandling();
         ImageURL url = new ImageURL();
        //TODO: call your test case functions one after other here

        //tests.testCase01();
        //search.amazonsearch();
         // count.hyperlinks();
        // linkpost.post();
         //name.namelinks();
        // imgpost.imagepost();
        //nesframes.frames();
        //alert.alerttext();
        //imdb.moviename();
        //handle.windows();
        url.imgurl();
        //END Tests
       // search.endTest();
         // count.endTest();
        // linkpost.endTest();
         //name.endTest();
        // imgpost.endTest();
        //nesframes.endTest();
        //alert.endTest();
        //imdb.endTest();
        //handle.endTest();
        url.endTest();



        //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
